-- Seed data for 2026 FIFA World Cup album (980 stickers)
INSERT INTO albums (id, name) VALUES (1, 'FIFA World Cup 2026') ON CONFLICT DO NOTHING;

INSERT INTO stickers (album_id, sticker_number, team_name, description, is_shiny) VALUES
(1, 'OP1', NULL, 'Panini Logo', TRUE),
(1, 'OP2', NULL, 'Official Emblem', TRUE),
(1, 'OP3', NULL, 'Official Mascot', TRUE),
(1, 'OP4', NULL, 'Tournament Slogan', TRUE),
(1, 'OP5', NULL, 'Official Match Ball', TRUE),
(1, 'OP6', NULL, 'Host City - USA', TRUE),
(1, 'OP7', NULL, 'Host City - Mexico', TRUE),
(1, 'OP8', NULL, 'Host City - Canada', TRUE),
(1, 'OP9', NULL, 'Trophy', TRUE),
(1, 'FWC1', NULL, 'Uruguay 1930 - World Cup History', TRUE),
(1, 'FWC2', NULL, 'Italy 1934 - World Cup History', TRUE),
(1, 'FWC3', NULL, 'Italy 1938 - World Cup History', TRUE),
(1, 'FWC4', NULL, 'Uruguay 1950 - World Cup History', TRUE),
(1, 'FWC5', NULL, 'West Germany 1954 - World Cup History', TRUE),
(1, 'FWC6', NULL, 'Brazil 1962 - World Cup History', TRUE),
(1, 'FWC7', NULL, 'England 1966 - World Cup History', TRUE),
(1, 'FWC8', NULL, 'West Germany 1974 - World Cup History', TRUE),
(1, 'FWC9', NULL, 'Argentina 1986 - World Cup History', TRUE),
(1, 'FWC10', NULL, 'Brazil 1994 - World Cup History', TRUE),
(1, 'FWC11', NULL, 'Argentina 2022 - World Cup History', TRUE),
(1, 'USA1', NULL, 'Team Badge - USA', TRUE),
(1, 'USA2', NULL, 'Player - USA', FALSE),
(1, 'USA3', NULL, 'Player - USA', FALSE),
(1, 'USA4', NULL, 'Player - USA', FALSE),
(1, 'USA5', NULL, 'Player - USA', FALSE),
(1, 'USA6', NULL, 'Player - USA', FALSE),
(1, 'USA7', NULL, 'Player - USA', FALSE),
(1, 'USA8', NULL, 'Player - USA', FALSE),
(1, 'USA9', NULL, 'Player - USA', FALSE),
(1, 'USA10', NULL, 'Player - USA', FALSE),
(1, 'USA11', NULL, 'Player - USA', FALSE),
(1, 'USA12', NULL, 'Player - USA', FALSE),
(1, 'USA13', NULL, 'Team Photo - USA', FALSE),
(1, 'USA14', NULL, 'Player - USA', FALSE),
(1, 'USA15', NULL, 'Player - USA', FALSE),
(1, 'USA16', NULL, 'Player - USA', FALSE),
(1, 'USA17', NULL, 'Player - USA', FALSE),
(1, 'USA18', NULL, 'Player - USA', FALSE),
(1, 'USA19', NULL, 'Player - USA', FALSE),
(1, 'USA20', NULL, 'Player - USA', FALSE),
(1, 'MEX1', NULL, 'Team Badge - Mexico', TRUE),
(1, 'MEX2', NULL, 'Player - Mexico', FALSE),
(1, 'MEX3', NULL, 'Player - Mexico', FALSE),
(1, 'MEX4', NULL, 'Player - Mexico', FALSE),
(1, 'MEX5', NULL, 'Player - Mexico', FALSE),
(1, 'MEX6', NULL, 'Player - Mexico', FALSE),
(1, 'MEX7', NULL, 'Player - Mexico', FALSE),
(1, 'MEX8', NULL, 'Player - Mexico', FALSE),
(1, 'MEX9', NULL, 'Player - Mexico', FALSE),
(1, 'MEX10', NULL, 'Player - Mexico', FALSE),
(1, 'MEX11', NULL, 'Player - Mexico', FALSE),
(1, 'MEX12', NULL, 'Player - Mexico', FALSE),
(1, 'MEX13', NULL, 'Team Photo - Mexico', FALSE),
(1, 'MEX14', NULL, 'Player - Mexico', FALSE),
(1, 'MEX15', NULL, 'Player - Mexico', FALSE),
(1, 'MEX16', NULL, 'Player - Mexico', FALSE),
(1, 'MEX17', NULL, 'Player - Mexico', FALSE),
(1, 'MEX18', NULL, 'Player - Mexico', FALSE),
(1, 'MEX19', NULL, 'Player - Mexico', FALSE),
(1, 'MEX20', NULL, 'Player - Mexico', FALSE),
(1, 'CAN1', NULL, 'Team Badge - Canada', TRUE),
(1, 'CAN2', NULL, 'Player - Canada', FALSE),
(1, 'CAN3', NULL, 'Player - Canada', FALSE),
(1, 'CAN4', NULL, 'Player - Canada', FALSE),
(1, 'CAN5', NULL, 'Player - Canada', FALSE),
(1, 'CAN6', NULL, 'Player - Canada', FALSE),
(1, 'CAN7', NULL, 'Player - Canada', FALSE),
(1, 'CAN8', NULL, 'Player - Canada', FALSE),
(1, 'CAN9', NULL, 'Player - Canada', FALSE),
(1, 'CAN10', NULL, 'Player - Canada', FALSE),
(1, 'CAN11', NULL, 'Player - Canada', FALSE),
(1, 'CAN12', NULL, 'Player - Canada', FALSE),
(1, 'CAN13', NULL, 'Team Photo - Canada', FALSE),
(1, 'CAN14', NULL, 'Player - Canada', FALSE),
(1, 'CAN15', NULL, 'Player - Canada', FALSE),
(1, 'CAN16', NULL, 'Player - Canada', FALSE),
(1, 'CAN17', NULL, 'Player - Canada', FALSE),
(1, 'CAN18', NULL, 'Player - Canada', FALSE),
(1, 'CAN19', NULL, 'Player - Canada', FALSE),
(1, 'CAN20', NULL, 'Player - Canada', FALSE),
(1, 'ARG1', NULL, 'Team Badge - Argentina', TRUE),
(1, 'ARG2', NULL, 'Player - Argentina', FALSE),
(1, 'ARG3', NULL, 'Player - Argentina', FALSE),
(1, 'ARG4', NULL, 'Player - Argentina', FALSE),
(1, 'ARG5', NULL, 'Player - Argentina', FALSE),
(1, 'ARG6', NULL, 'Player - Argentina', FALSE),
(1, 'ARG7', NULL, 'Player - Argentina', FALSE),
(1, 'ARG8', NULL, 'Player - Argentina', FALSE),
(1, 'ARG9', NULL, 'Player - Argentina', FALSE),
(1, 'ARG10', NULL, 'Player - Argentina', FALSE),
(1, 'ARG11', NULL, 'Player - Argentina', FALSE),
(1, 'ARG12', NULL, 'Player - Argentina', FALSE),
(1, 'ARG13', NULL, 'Team Photo - Argentina', FALSE),
(1, 'ARG14', NULL, 'Player - Argentina', FALSE),
(1, 'ARG15', NULL, 'Player - Argentina', FALSE),
(1, 'ARG16', NULL, 'Player - Argentina', FALSE),
(1, 'ARG17', NULL, 'Player - Argentina', FALSE),
(1, 'ARG18', NULL, 'Player - Argentina', FALSE),
(1, 'ARG19', NULL, 'Player - Argentina', FALSE),
(1, 'ARG20', NULL, 'Player - Argentina', FALSE),
(1, 'BRA1', NULL, 'Team Badge - Brazil', TRUE),
(1, 'BRA2', NULL, 'Player - Brazil', FALSE),
(1, 'BRA3', NULL, 'Player - Brazil', FALSE),
(1, 'BRA4', NULL, 'Player - Brazil', FALSE),
(1, 'BRA5', NULL, 'Player - Brazil', FALSE),
(1, 'BRA6', NULL, 'Player - Brazil', FALSE),
(1, 'BRA7', NULL, 'Player - Brazil', FALSE),
(1, 'BRA8', NULL, 'Player - Brazil', FALSE),
(1, 'BRA9', NULL, 'Player - Brazil', FALSE),
(1, 'BRA10', NULL, 'Player - Brazil', FALSE),
(1, 'BRA11', NULL, 'Player - Brazil', FALSE),
(1, 'BRA12', NULL, 'Player - Brazil', FALSE),
(1, 'BRA13', NULL, 'Team Photo - Brazil', FALSE),
(1, 'BRA14', NULL, 'Player - Brazil', FALSE),
(1, 'BRA15', NULL, 'Player - Brazil', FALSE),
(1, 'BRA16', NULL, 'Player - Brazil', FALSE),
(1, 'BRA17', NULL, 'Player - Brazil', FALSE),
(1, 'BRA18', NULL, 'Player - Brazil', FALSE),
(1, 'BRA19', NULL, 'Player - Brazil', FALSE),
(1, 'BRA20', NULL, 'Player - Brazil', FALSE),
(1, 'FRA1', NULL, 'Team Badge - France', TRUE),
(1, 'FRA2', NULL, 'Player - France', FALSE),
(1, 'FRA3', NULL, 'Player - France', FALSE),
(1, 'FRA4', NULL, 'Player - France', FALSE),
(1, 'FRA5', NULL, 'Player - France', FALSE),
(1, 'FRA6', NULL, 'Player - France', FALSE),
(1, 'FRA7', NULL, 'Player - France', FALSE),
(1, 'FRA8', NULL, 'Player - France', FALSE),
(1, 'FRA9', NULL, 'Player - France', FALSE),
(1, 'FRA10', NULL, 'Player - France', FALSE),
(1, 'FRA11', NULL, 'Player - France', FALSE),
(1, 'FRA12', NULL, 'Player - France', FALSE),
(1, 'FRA13', NULL, 'Team Photo - France', FALSE),
(1, 'FRA14', NULL, 'Player - France', FALSE),
(1, 'FRA15', NULL, 'Player - France', FALSE),
(1, 'FRA16', NULL, 'Player - France', FALSE),
(1, 'FRA17', NULL, 'Player - France', FALSE),
(1, 'FRA18', NULL, 'Player - France', FALSE),
(1, 'FRA19', NULL, 'Player - France', FALSE),
(1, 'FRA20', NULL, 'Player - France', FALSE),
(1, 'ENG1', NULL, 'Team Badge - England', TRUE),
(1, 'ENG2', NULL, 'Player - England', FALSE),
(1, 'ENG3', NULL, 'Player - England', FALSE),
(1, 'ENG4', NULL, 'Player - England', FALSE),
(1, 'ENG5', NULL, 'Player - England', FALSE),
(1, 'ENG6', NULL, 'Player - England', FALSE),
(1, 'ENG7', NULL, 'Player - England', FALSE),
(1, 'ENG8', NULL, 'Player - England', FALSE),
(1, 'ENG9', NULL, 'Player - England', FALSE),
(1, 'ENG10', NULL, 'Player - England', FALSE),
(1, 'ENG11', NULL, 'Player - England', FALSE),
(1, 'ENG12', NULL, 'Player - England', FALSE),
(1, 'ENG13', NULL, 'Team Photo - England', FALSE),
(1, 'ENG14', NULL, 'Player - England', FALSE),
(1, 'ENG15', NULL, 'Player - England', FALSE),
(1, 'ENG16', NULL, 'Player - England', FALSE),
(1, 'ENG17', NULL, 'Player - England', FALSE),
(1, 'ENG18', NULL, 'Player - England', FALSE),
(1, 'ENG19', NULL, 'Player - England', FALSE),
(1, 'ENG20', NULL, 'Player - England', FALSE),
(1, 'SPA1', NULL, 'Team Badge - Spain', TRUE),
(1, 'SPA2', NULL, 'Player - Spain', FALSE),
(1, 'SPA3', NULL, 'Player - Spain', FALSE),
(1, 'SPA4', NULL, 'Player - Spain', FALSE),
(1, 'SPA5', NULL, 'Player - Spain', FALSE),
(1, 'SPA6', NULL, 'Player - Spain', FALSE),
(1, 'SPA7', NULL, 'Player - Spain', FALSE),
(1, 'SPA8', NULL, 'Player - Spain', FALSE),
(1, 'SPA9', NULL, 'Player - Spain', FALSE),
(1, 'SPA10', NULL, 'Player - Spain', FALSE),
(1, 'SPA11', NULL, 'Player - Spain', FALSE),
(1, 'SPA12', NULL, 'Player - Spain', FALSE),
(1, 'SPA13', NULL, 'Team Photo - Spain', FALSE),
(1, 'SPA14', NULL, 'Player - Spain', FALSE),
(1, 'SPA15', NULL, 'Player - Spain', FALSE),
(1, 'SPA16', NULL, 'Player - Spain', FALSE),
(1, 'SPA17', NULL, 'Player - Spain', FALSE),
(1, 'SPA18', NULL, 'Player - Spain', FALSE),
(1, 'SPA19', NULL, 'Player - Spain', FALSE),
(1, 'SPA20', NULL, 'Player - Spain', FALSE),
(1, 'GER1', NULL, 'Team Badge - Germany', TRUE),
(1, 'GER2', NULL, 'Player - Germany', FALSE),
(1, 'GER3', NULL, 'Player - Germany', FALSE),
(1, 'GER4', NULL, 'Player - Germany', FALSE),
(1, 'GER5', NULL, 'Player - Germany', FALSE),
(1, 'GER6', NULL, 'Player - Germany', FALSE),
(1, 'GER7', NULL, 'Player - Germany', FALSE),
(1, 'GER8', NULL, 'Player - Germany', FALSE),
(1, 'GER9', NULL, 'Player - Germany', FALSE),
(1, 'GER10', NULL, 'Player - Germany', FALSE),
(1, 'GER11', NULL, 'Player - Germany', FALSE),
(1, 'GER12', NULL, 'Player - Germany', FALSE),
(1, 'GER13', NULL, 'Team Photo - Germany', FALSE),
(1, 'GER14', NULL, 'Player - Germany', FALSE),
(1, 'GER15', NULL, 'Player - Germany', FALSE),
(1, 'GER16', NULL, 'Player - Germany', FALSE),
(1, 'GER17', NULL, 'Player - Germany', FALSE),
(1, 'GER18', NULL, 'Player - Germany', FALSE),
(1, 'GER19', NULL, 'Player - Germany', FALSE),
(1, 'GER20', NULL, 'Player - Germany', FALSE),
(1, 'POR1', NULL, 'Team Badge - Portugal', TRUE),
(1, 'POR2', NULL, 'Player - Portugal', FALSE),
(1, 'POR3', NULL, 'Player - Portugal', FALSE),
(1, 'POR4', NULL, 'Player - Portugal', FALSE),
(1, 'POR5', NULL, 'Player - Portugal', FALSE),
(1, 'POR6', NULL, 'Player - Portugal', FALSE),
(1, 'POR7', NULL, 'Player - Portugal', FALSE),
(1, 'POR8', NULL, 'Player - Portugal', FALSE),
(1, 'POR9', NULL, 'Player - Portugal', FALSE),
(1, 'POR10', NULL, 'Player - Portugal', FALSE),
(1, 'POR11', NULL, 'Player - Portugal', FALSE),
(1, 'POR12', NULL, 'Player - Portugal', FALSE),
(1, 'POR13', NULL, 'Team Photo - Portugal', FALSE),
(1, 'POR14', NULL, 'Player - Portugal', FALSE),
(1, 'POR15', NULL, 'Player - Portugal', FALSE),
(1, 'POR16', NULL, 'Player - Portugal', FALSE),
(1, 'POR17', NULL, 'Player - Portugal', FALSE),
(1, 'POR18', NULL, 'Player - Portugal', FALSE),
(1, 'POR19', NULL, 'Player - Portugal', FALSE),
(1, 'POR20', NULL, 'Player - Portugal', FALSE),
(1, 'NET1', NULL, 'Team Badge - Netherlands', TRUE),
(1, 'NET2', NULL, 'Player - Netherlands', FALSE),
(1, 'NET3', NULL, 'Player - Netherlands', FALSE),
(1, 'NET4', NULL, 'Player - Netherlands', FALSE),
(1, 'NET5', NULL, 'Player - Netherlands', FALSE),
(1, 'NET6', NULL, 'Player - Netherlands', FALSE),
(1, 'NET7', NULL, 'Player - Netherlands', FALSE),
(1, 'NET8', NULL, 'Player - Netherlands', FALSE),
(1, 'NET9', NULL, 'Player - Netherlands', FALSE),
(1, 'NET10', NULL, 'Player - Netherlands', FALSE),
(1, 'NET11', NULL, 'Player - Netherlands', FALSE),
(1, 'NET12', NULL, 'Player - Netherlands', FALSE),
(1, 'NET13', NULL, 'Team Photo - Netherlands', FALSE),
(1, 'NET14', NULL, 'Player - Netherlands', FALSE),
(1, 'NET15', NULL, 'Player - Netherlands', FALSE),
(1, 'NET16', NULL, 'Player - Netherlands', FALSE),
(1, 'NET17', NULL, 'Player - Netherlands', FALSE),
(1, 'NET18', NULL, 'Player - Netherlands', FALSE),
(1, 'NET19', NULL, 'Player - Netherlands', FALSE),
(1, 'NET20', NULL, 'Player - Netherlands', FALSE),
(1, 'BEL1', NULL, 'Team Badge - Belgium', TRUE),
(1, 'BEL2', NULL, 'Player - Belgium', FALSE),
(1, 'BEL3', NULL, 'Player - Belgium', FALSE),
(1, 'BEL4', NULL, 'Player - Belgium', FALSE),
(1, 'BEL5', NULL, 'Player - Belgium', FALSE),
(1, 'BEL6', NULL, 'Player - Belgium', FALSE),
(1, 'BEL7', NULL, 'Player - Belgium', FALSE),
(1, 'BEL8', NULL, 'Player - Belgium', FALSE),
(1, 'BEL9', NULL, 'Player - Belgium', FALSE),
(1, 'BEL10', NULL, 'Player - Belgium', FALSE),
(1, 'BEL11', NULL, 'Player - Belgium', FALSE),
(1, 'BEL12', NULL, 'Player - Belgium', FALSE),
(1, 'BEL13', NULL, 'Team Photo - Belgium', FALSE),
(1, 'BEL14', NULL, 'Player - Belgium', FALSE),
(1, 'BEL15', NULL, 'Player - Belgium', FALSE),
(1, 'BEL16', NULL, 'Player - Belgium', FALSE),
(1, 'BEL17', NULL, 'Player - Belgium', FALSE),
(1, 'BEL18', NULL, 'Player - Belgium', FALSE),
(1, 'BEL19', NULL, 'Player - Belgium', FALSE),
(1, 'BEL20', NULL, 'Player - Belgium', FALSE),
(1, 'ITA1', NULL, 'Team Badge - Italy', TRUE),
(1, 'ITA2', NULL, 'Player - Italy', FALSE),
(1, 'ITA3', NULL, 'Player - Italy', FALSE),
(1, 'ITA4', NULL, 'Player - Italy', FALSE),
(1, 'ITA5', NULL, 'Player - Italy', FALSE),
(1, 'ITA6', NULL, 'Player - Italy', FALSE),
(1, 'ITA7', NULL, 'Player - Italy', FALSE),
(1, 'ITA8', NULL, 'Player - Italy', FALSE),
(1, 'ITA9', NULL, 'Player - Italy', FALSE),
(1, 'ITA10', NULL, 'Player - Italy', FALSE),
(1, 'ITA11', NULL, 'Player - Italy', FALSE),
(1, 'ITA12', NULL, 'Player - Italy', FALSE),
(1, 'ITA13', NULL, 'Team Photo - Italy', FALSE),
(1, 'ITA14', NULL, 'Player - Italy', FALSE),
(1, 'ITA15', NULL, 'Player - Italy', FALSE),
(1, 'ITA16', NULL, 'Player - Italy', FALSE),
(1, 'ITA17', NULL, 'Player - Italy', FALSE),
(1, 'ITA18', NULL, 'Player - Italy', FALSE),
(1, 'ITA19', NULL, 'Player - Italy', FALSE),
(1, 'ITA20', NULL, 'Player - Italy', FALSE),
(1, 'CRO1', NULL, 'Team Badge - Croatia', TRUE),
(1, 'CRO2', NULL, 'Player - Croatia', FALSE),
(1, 'CRO3', NULL, 'Player - Croatia', FALSE),
(1, 'CRO4', NULL, 'Player - Croatia', FALSE),
(1, 'CRO5', NULL, 'Player - Croatia', FALSE),
(1, 'CRO6', NULL, 'Player - Croatia', FALSE),
(1, 'CRO7', NULL, 'Player - Croatia', FALSE),
(1, 'CRO8', NULL, 'Player - Croatia', FALSE),
(1, 'CRO9', NULL, 'Player - Croatia', FALSE),
(1, 'CRO10', NULL, 'Player - Croatia', FALSE),
(1, 'CRO11', NULL, 'Player - Croatia', FALSE),
(1, 'CRO12', NULL, 'Player - Croatia', FALSE),
(1, 'CRO13', NULL, 'Team Photo - Croatia', FALSE),
(1, 'CRO14', NULL, 'Player - Croatia', FALSE),
(1, 'CRO15', NULL, 'Player - Croatia', FALSE),
(1, 'CRO16', NULL, 'Player - Croatia', FALSE),
(1, 'CRO17', NULL, 'Player - Croatia', FALSE),
(1, 'CRO18', NULL, 'Player - Croatia', FALSE),
(1, 'CRO19', NULL, 'Player - Croatia', FALSE),
(1, 'CRO20', NULL, 'Player - Croatia', FALSE),
(1, 'URU1', NULL, 'Team Badge - Uruguay', TRUE),
(1, 'URU2', NULL, 'Player - Uruguay', FALSE),
(1, 'URU3', NULL, 'Player - Uruguay', FALSE),
(1, 'URU4', NULL, 'Player - Uruguay', FALSE),
(1, 'URU5', NULL, 'Player - Uruguay', FALSE),
(1, 'URU6', NULL, 'Player - Uruguay', FALSE),
(1, 'URU7', NULL, 'Player - Uruguay', FALSE),
(1, 'URU8', NULL, 'Player - Uruguay', FALSE),
(1, 'URU9', NULL, 'Player - Uruguay', FALSE),
(1, 'URU10', NULL, 'Player - Uruguay', FALSE),
(1, 'URU11', NULL, 'Player - Uruguay', FALSE),
(1, 'URU12', NULL, 'Player - Uruguay', FALSE),
(1, 'URU13', NULL, 'Team Photo - Uruguay', FALSE),
(1, 'URU14', NULL, 'Player - Uruguay', FALSE),
(1, 'URU15', NULL, 'Player - Uruguay', FALSE),
(1, 'URU16', NULL, 'Player - Uruguay', FALSE),
(1, 'URU17', NULL, 'Player - Uruguay', FALSE),
(1, 'URU18', NULL, 'Player - Uruguay', FALSE),
(1, 'URU19', NULL, 'Player - Uruguay', FALSE),
(1, 'URU20', NULL, 'Player - Uruguay', FALSE),
(1, 'COL1', NULL, 'Team Badge - Colombia', TRUE),
(1, 'COL2', NULL, 'Player - Colombia', FALSE),
(1, 'COL3', NULL, 'Player - Colombia', FALSE),
(1, 'COL4', NULL, 'Player - Colombia', FALSE),
(1, 'COL5', NULL, 'Player - Colombia', FALSE),
(1, 'COL6', NULL, 'Player - Colombia', FALSE),
(1, 'COL7', NULL, 'Player - Colombia', FALSE),
(1, 'COL8', NULL, 'Player - Colombia', FALSE),
(1, 'COL9', NULL, 'Player - Colombia', FALSE),
(1, 'COL10', NULL, 'Player - Colombia', FALSE),
(1, 'COL11', NULL, 'Player - Colombia', FALSE),
(1, 'COL12', NULL, 'Player - Colombia', FALSE),
(1, 'COL13', NULL, 'Team Photo - Colombia', FALSE),
(1, 'COL14', NULL, 'Player - Colombia', FALSE),
(1, 'COL15', NULL, 'Player - Colombia', FALSE),
(1, 'COL16', NULL, 'Player - Colombia', FALSE),
(1, 'COL17', NULL, 'Player - Colombia', FALSE),
(1, 'COL18', NULL, 'Player - Colombia', FALSE),
(1, 'COL19', NULL, 'Player - Colombia', FALSE),
(1, 'COL20', NULL, 'Player - Colombia', FALSE),
(1, 'JAP1', NULL, 'Team Badge - Japan', TRUE),
(1, 'JAP2', NULL, 'Player - Japan', FALSE),
(1, 'JAP3', NULL, 'Player - Japan', FALSE),
(1, 'JAP4', NULL, 'Player - Japan', FALSE),
(1, 'JAP5', NULL, 'Player - Japan', FALSE),
(1, 'JAP6', NULL, 'Player - Japan', FALSE),
(1, 'JAP7', NULL, 'Player - Japan', FALSE),
(1, 'JAP8', NULL, 'Player - Japan', FALSE),
(1, 'JAP9', NULL, 'Player - Japan', FALSE),
(1, 'JAP10', NULL, 'Player - Japan', FALSE),
(1, 'JAP11', NULL, 'Player - Japan', FALSE),
(1, 'JAP12', NULL, 'Player - Japan', FALSE),
(1, 'JAP13', NULL, 'Team Photo - Japan', FALSE),
(1, 'JAP14', NULL, 'Player - Japan', FALSE),
(1, 'JAP15', NULL, 'Player - Japan', FALSE),
(1, 'JAP16', NULL, 'Player - Japan', FALSE),
(1, 'JAP17', NULL, 'Player - Japan', FALSE),
(1, 'JAP18', NULL, 'Player - Japan', FALSE),
(1, 'JAP19', NULL, 'Player - Japan', FALSE),
(1, 'JAP20', NULL, 'Player - Japan', FALSE),
(1, 'SOU1', NULL, 'Team Badge - South Korea', TRUE),
(1, 'SOU2', NULL, 'Player - South Korea', FALSE),
(1, 'SOU3', NULL, 'Player - South Korea', FALSE),
(1, 'SOU4', NULL, 'Player - South Korea', FALSE),
(1, 'SOU5', NULL, 'Player - South Korea', FALSE),
(1, 'SOU6', NULL, 'Player - South Korea', FALSE),
(1, 'SOU7', NULL, 'Player - South Korea', FALSE),
(1, 'SOU8', NULL, 'Player - South Korea', FALSE),
(1, 'SOU9', NULL, 'Player - South Korea', FALSE),
(1, 'SOU10', NULL, 'Player - South Korea', FALSE),
(1, 'SOU11', NULL, 'Player - South Korea', FALSE),
(1, 'SOU12', NULL, 'Player - South Korea', FALSE),
(1, 'SOU13', NULL, 'Team Photo - South Korea', FALSE),
(1, 'SOU14', NULL, 'Player - South Korea', FALSE),
(1, 'SOU15', NULL, 'Player - South Korea', FALSE),
(1, 'SOU16', NULL, 'Player - South Korea', FALSE),
(1, 'SOU17', NULL, 'Player - South Korea', FALSE),
(1, 'SOU18', NULL, 'Player - South Korea', FALSE),
(1, 'SOU19', NULL, 'Player - South Korea', FALSE),
(1, 'SOU20', NULL, 'Player - South Korea', FALSE),
(1, 'MOR1', NULL, 'Team Badge - Morocco', TRUE),
(1, 'MOR2', NULL, 'Player - Morocco', FALSE),
(1, 'MOR3', NULL, 'Player - Morocco', FALSE),
(1, 'MOR4', NULL, 'Player - Morocco', FALSE),
(1, 'MOR5', NULL, 'Player - Morocco', FALSE),
(1, 'MOR6', NULL, 'Player - Morocco', FALSE),
(1, 'MOR7', NULL, 'Player - Morocco', FALSE),
(1, 'MOR8', NULL, 'Player - Morocco', FALSE),
(1, 'MOR9', NULL, 'Player - Morocco', FALSE),
(1, 'MOR10', NULL, 'Player - Morocco', FALSE),
(1, 'MOR11', NULL, 'Player - Morocco', FALSE),
(1, 'MOR12', NULL, 'Player - Morocco', FALSE),
(1, 'MOR13', NULL, 'Team Photo - Morocco', FALSE),
(1, 'MOR14', NULL, 'Player - Morocco', FALSE),
(1, 'MOR15', NULL, 'Player - Morocco', FALSE),
(1, 'MOR16', NULL, 'Player - Morocco', FALSE),
(1, 'MOR17', NULL, 'Player - Morocco', FALSE),
(1, 'MOR18', NULL, 'Player - Morocco', FALSE),
(1, 'MOR19', NULL, 'Player - Morocco', FALSE),
(1, 'MOR20', NULL, 'Player - Morocco', FALSE),
(1, 'SEN1', NULL, 'Team Badge - Senegal', TRUE),
(1, 'SEN2', NULL, 'Player - Senegal', FALSE),
(1, 'SEN3', NULL, 'Player - Senegal', FALSE),
(1, 'SEN4', NULL, 'Player - Senegal', FALSE),
(1, 'SEN5', NULL, 'Player - Senegal', FALSE),
(1, 'SEN6', NULL, 'Player - Senegal', FALSE),
(1, 'SEN7', NULL, 'Player - Senegal', FALSE),
(1, 'SEN8', NULL, 'Player - Senegal', FALSE),
(1, 'SEN9', NULL, 'Player - Senegal', FALSE),
(1, 'SEN10', NULL, 'Player - Senegal', FALSE),
(1, 'SEN11', NULL, 'Player - Senegal', FALSE),
(1, 'SEN12', NULL, 'Player - Senegal', FALSE),
(1, 'SEN13', NULL, 'Team Photo - Senegal', FALSE),
(1, 'SEN14', NULL, 'Player - Senegal', FALSE),
(1, 'SEN15', NULL, 'Player - Senegal', FALSE),
(1, 'SEN16', NULL, 'Player - Senegal', FALSE),
(1, 'SEN17', NULL, 'Player - Senegal', FALSE),
(1, 'SEN18', NULL, 'Player - Senegal', FALSE),
(1, 'SEN19', NULL, 'Player - Senegal', FALSE),
(1, 'SEN20', NULL, 'Player - Senegal', FALSE),
(1, 'SWI1', NULL, 'Team Badge - Switzerland', TRUE),
(1, 'SWI2', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI3', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI4', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI5', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI6', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI7', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI8', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI9', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI10', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI11', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI12', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI13', NULL, 'Team Photo - Switzerland', FALSE),
(1, 'SWI14', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI15', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI16', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI17', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI18', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI19', NULL, 'Player - Switzerland', FALSE),
(1, 'SWI20', NULL, 'Player - Switzerland', FALSE),
(1, 'DEN1', NULL, 'Team Badge - Denmark', TRUE),
(1, 'DEN2', NULL, 'Player - Denmark', FALSE),
(1, 'DEN3', NULL, 'Player - Denmark', FALSE),
(1, 'DEN4', NULL, 'Player - Denmark', FALSE),
(1, 'DEN5', NULL, 'Player - Denmark', FALSE),
(1, 'DEN6', NULL, 'Player - Denmark', FALSE),
(1, 'DEN7', NULL, 'Player - Denmark', FALSE),
(1, 'DEN8', NULL, 'Player - Denmark', FALSE),
(1, 'DEN9', NULL, 'Player - Denmark', FALSE),
(1, 'DEN10', NULL, 'Player - Denmark', FALSE),
(1, 'DEN11', NULL, 'Player - Denmark', FALSE),
(1, 'DEN12', NULL, 'Player - Denmark', FALSE),
(1, 'DEN13', NULL, 'Team Photo - Denmark', FALSE),
(1, 'DEN14', NULL, 'Player - Denmark', FALSE),
(1, 'DEN15', NULL, 'Player - Denmark', FALSE),
(1, 'DEN16', NULL, 'Player - Denmark', FALSE),
(1, 'DEN17', NULL, 'Player - Denmark', FALSE),
(1, 'DEN18', NULL, 'Player - Denmark', FALSE),
(1, 'DEN19', NULL, 'Player - Denmark', FALSE),
(1, 'DEN20', NULL, 'Player - Denmark', FALSE),
(1, 'POL1', NULL, 'Team Badge - Poland', TRUE),
(1, 'POL2', NULL, 'Player - Poland', FALSE),
(1, 'POL3', NULL, 'Player - Poland', FALSE),
(1, 'POL4', NULL, 'Player - Poland', FALSE),
(1, 'POL5', NULL, 'Player - Poland', FALSE),
(1, 'POL6', NULL, 'Player - Poland', FALSE),
(1, 'POL7', NULL, 'Player - Poland', FALSE),
(1, 'POL8', NULL, 'Player - Poland', FALSE),
(1, 'POL9', NULL, 'Player - Poland', FALSE),
(1, 'POL10', NULL, 'Player - Poland', FALSE),
(1, 'POL11', NULL, 'Player - Poland', FALSE),
(1, 'POL12', NULL, 'Player - Poland', FALSE),
(1, 'POL13', NULL, 'Team Photo - Poland', FALSE),
(1, 'POL14', NULL, 'Player - Poland', FALSE),
(1, 'POL15', NULL, 'Player - Poland', FALSE),
(1, 'POL16', NULL, 'Player - Poland', FALSE),
(1, 'POL17', NULL, 'Player - Poland', FALSE),
(1, 'POL18', NULL, 'Player - Poland', FALSE),
(1, 'POL19', NULL, 'Player - Poland', FALSE),
(1, 'POL20', NULL, 'Player - Poland', FALSE),
(1, 'AUS1', NULL, 'Team Badge - Australia', TRUE),
(1, 'AUS2', NULL, 'Player - Australia', FALSE),
(1, 'AUS3', NULL, 'Player - Australia', FALSE),
(1, 'AUS4', NULL, 'Player - Australia', FALSE),
(1, 'AUS5', NULL, 'Player - Australia', FALSE),
(1, 'AUS6', NULL, 'Player - Australia', FALSE),
(1, 'AUS7', NULL, 'Player - Australia', FALSE),
(1, 'AUS8', NULL, 'Player - Australia', FALSE),
(1, 'AUS9', NULL, 'Player - Australia', FALSE),
(1, 'AUS10', NULL, 'Player - Australia', FALSE),
(1, 'AUS11', NULL, 'Player - Australia', FALSE),
(1, 'AUS12', NULL, 'Player - Australia', FALSE),
(1, 'AUS13', NULL, 'Team Photo - Australia', FALSE),
(1, 'AUS14', NULL, 'Player - Australia', FALSE),
(1, 'AUS15', NULL, 'Player - Australia', FALSE),
(1, 'AUS16', NULL, 'Player - Australia', FALSE),
(1, 'AUS17', NULL, 'Player - Australia', FALSE),
(1, 'AUS18', NULL, 'Player - Australia', FALSE),
(1, 'AUS19', NULL, 'Player - Australia', FALSE),
(1, 'AUS20', NULL, 'Player - Australia', FALSE),
(1, 'ECU1', NULL, 'Team Badge - Ecuador', TRUE),
(1, 'ECU2', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU3', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU4', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU5', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU6', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU7', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU8', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU9', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU10', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU11', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU12', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU13', NULL, 'Team Photo - Ecuador', FALSE),
(1, 'ECU14', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU15', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU16', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU17', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU18', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU19', NULL, 'Player - Ecuador', FALSE),
(1, 'ECU20', NULL, 'Player - Ecuador', FALSE),
(1, 'IRA1', NULL, 'Team Badge - Iran', TRUE),
(1, 'IRA2', NULL, 'Player - Iran', FALSE),
(1, 'IRA3', NULL, 'Player - Iran', FALSE),
(1, 'IRA4', NULL, 'Player - Iran', FALSE),
(1, 'IRA5', NULL, 'Player - Iran', FALSE),
(1, 'IRA6', NULL, 'Player - Iran', FALSE),
(1, 'IRA7', NULL, 'Player - Iran', FALSE),
(1, 'IRA8', NULL, 'Player - Iran', FALSE),
(1, 'IRA9', NULL, 'Player - Iran', FALSE),
(1, 'IRA10', NULL, 'Player - Iran', FALSE),
(1, 'IRA11', NULL, 'Player - Iran', FALSE),
(1, 'IRA12', NULL, 'Player - Iran', FALSE),
(1, 'IRA13', NULL, 'Team Photo - Iran', FALSE),
(1, 'IRA14', NULL, 'Player - Iran', FALSE),
(1, 'IRA15', NULL, 'Player - Iran', FALSE),
(1, 'IRA16', NULL, 'Player - Iran', FALSE),
(1, 'IRA17', NULL, 'Player - Iran', FALSE),
(1, 'IRA18', NULL, 'Player - Iran', FALSE),
(1, 'IRA19', NULL, 'Player - Iran', FALSE),
(1, 'IRA20', NULL, 'Player - Iran', FALSE),
(1, 'SAU1', NULL, 'Team Badge - Saudi Arabia', TRUE),
(1, 'SAU2', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU3', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU4', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU5', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU6', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU7', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU8', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU9', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU10', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU11', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU12', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU13', NULL, 'Team Photo - Saudi Arabia', FALSE),
(1, 'SAU14', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU15', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU16', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU17', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU18', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU19', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'SAU20', NULL, 'Player - Saudi Arabia', FALSE),
(1, 'QAT1', NULL, 'Team Badge - Qatar', TRUE),
(1, 'QAT2', NULL, 'Player - Qatar', FALSE),
(1, 'QAT3', NULL, 'Player - Qatar', FALSE),
(1, 'QAT4', NULL, 'Player - Qatar', FALSE),
(1, 'QAT5', NULL, 'Player - Qatar', FALSE),
(1, 'QAT6', NULL, 'Player - Qatar', FALSE),
(1, 'QAT7', NULL, 'Player - Qatar', FALSE),
(1, 'QAT8', NULL, 'Player - Qatar', FALSE),
(1, 'QAT9', NULL, 'Player - Qatar', FALSE),
(1, 'QAT10', NULL, 'Player - Qatar', FALSE),
(1, 'QAT11', NULL, 'Player - Qatar', FALSE),
(1, 'QAT12', NULL, 'Player - Qatar', FALSE),
(1, 'QAT13', NULL, 'Team Photo - Qatar', FALSE),
(1, 'QAT14', NULL, 'Player - Qatar', FALSE),
(1, 'QAT15', NULL, 'Player - Qatar', FALSE),
(1, 'QAT16', NULL, 'Player - Qatar', FALSE),
(1, 'QAT17', NULL, 'Player - Qatar', FALSE),
(1, 'QAT18', NULL, 'Player - Qatar', FALSE),
(1, 'QAT19', NULL, 'Player - Qatar', FALSE),
(1, 'QAT20', NULL, 'Player - Qatar', FALSE),
(1, 'TUN1', NULL, 'Team Badge - Tunisia', TRUE),
(1, 'TUN2', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN3', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN4', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN5', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN6', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN7', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN8', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN9', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN10', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN11', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN12', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN13', NULL, 'Team Photo - Tunisia', FALSE),
(1, 'TUN14', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN15', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN16', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN17', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN18', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN19', NULL, 'Player - Tunisia', FALSE),
(1, 'TUN20', NULL, 'Player - Tunisia', FALSE),
(1, 'GHA1', NULL, 'Team Badge - Ghana', TRUE),
(1, 'GHA2', NULL, 'Player - Ghana', FALSE),
(1, 'GHA3', NULL, 'Player - Ghana', FALSE),
(1, 'GHA4', NULL, 'Player - Ghana', FALSE),
(1, 'GHA5', NULL, 'Player - Ghana', FALSE),
(1, 'GHA6', NULL, 'Player - Ghana', FALSE),
(1, 'GHA7', NULL, 'Player - Ghana', FALSE),
(1, 'GHA8', NULL, 'Player - Ghana', FALSE),
(1, 'GHA9', NULL, 'Player - Ghana', FALSE),
(1, 'GHA10', NULL, 'Player - Ghana', FALSE),
(1, 'GHA11', NULL, 'Player - Ghana', FALSE),
(1, 'GHA12', NULL, 'Player - Ghana', FALSE),
(1, 'GHA13', NULL, 'Team Photo - Ghana', FALSE),
(1, 'GHA14', NULL, 'Player - Ghana', FALSE),
(1, 'GHA15', NULL, 'Player - Ghana', FALSE),
(1, 'GHA16', NULL, 'Player - Ghana', FALSE),
(1, 'GHA17', NULL, 'Player - Ghana', FALSE),
(1, 'GHA18', NULL, 'Player - Ghana', FALSE),
(1, 'GHA19', NULL, 'Player - Ghana', FALSE),
(1, 'GHA20', NULL, 'Player - Ghana', FALSE),
(1, 'CAM1', NULL, 'Team Badge - Cameroon', TRUE),
(1, 'CAM2', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM3', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM4', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM5', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM6', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM7', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM8', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM9', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM10', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM11', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM12', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM13', NULL, 'Team Photo - Cameroon', FALSE),
(1, 'CAM14', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM15', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM16', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM17', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM18', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM19', NULL, 'Player - Cameroon', FALSE),
(1, 'CAM20', NULL, 'Player - Cameroon', FALSE),
(1, 'WAL1', NULL, 'Team Badge - Wales', TRUE),
(1, 'WAL2', NULL, 'Player - Wales', FALSE),
(1, 'WAL3', NULL, 'Player - Wales', FALSE),
(1, 'WAL4', NULL, 'Player - Wales', FALSE),
(1, 'WAL5', NULL, 'Player - Wales', FALSE),
(1, 'WAL6', NULL, 'Player - Wales', FALSE),
(1, 'WAL7', NULL, 'Player - Wales', FALSE),
(1, 'WAL8', NULL, 'Player - Wales', FALSE),
(1, 'WAL9', NULL, 'Player - Wales', FALSE),
(1, 'WAL10', NULL, 'Player - Wales', FALSE),
(1, 'WAL11', NULL, 'Player - Wales', FALSE),
(1, 'WAL12', NULL, 'Player - Wales', FALSE),
(1, 'WAL13', NULL, 'Team Photo - Wales', FALSE),
(1, 'WAL14', NULL, 'Player - Wales', FALSE),
(1, 'WAL15', NULL, 'Player - Wales', FALSE),
(1, 'WAL16', NULL, 'Player - Wales', FALSE),
(1, 'WAL17', NULL, 'Player - Wales', FALSE),
(1, 'WAL18', NULL, 'Player - Wales', FALSE),
(1, 'WAL19', NULL, 'Player - Wales', FALSE),
(1, 'WAL20', NULL, 'Player - Wales', FALSE),
(1, 'SER1', NULL, 'Team Badge - Serbia', TRUE),
(1, 'SER2', NULL, 'Player - Serbia', FALSE),
(1, 'SER3', NULL, 'Player - Serbia', FALSE),
(1, 'SER4', NULL, 'Player - Serbia', FALSE),
(1, 'SER5', NULL, 'Player - Serbia', FALSE),
(1, 'SER6', NULL, 'Player - Serbia', FALSE),
(1, 'SER7', NULL, 'Player - Serbia', FALSE),
(1, 'SER8', NULL, 'Player - Serbia', FALSE),
(1, 'SER9', NULL, 'Player - Serbia', FALSE),
(1, 'SER10', NULL, 'Player - Serbia', FALSE),
(1, 'SER11', NULL, 'Player - Serbia', FALSE),
(1, 'SER12', NULL, 'Player - Serbia', FALSE),
(1, 'SER13', NULL, 'Team Photo - Serbia', FALSE),
(1, 'SER14', NULL, 'Player - Serbia', FALSE),
(1, 'SER15', NULL, 'Player - Serbia', FALSE),
(1, 'SER16', NULL, 'Player - Serbia', FALSE),
(1, 'SER17', NULL, 'Player - Serbia', FALSE),
(1, 'SER18', NULL, 'Player - Serbia', FALSE),
(1, 'SER19', NULL, 'Player - Serbia', FALSE),
(1, 'SER20', NULL, 'Player - Serbia', FALSE),
(1, 'COS1', NULL, 'Team Badge - Costa Rica', TRUE),
(1, 'COS2', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS3', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS4', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS5', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS6', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS7', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS8', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS9', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS10', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS11', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS12', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS13', NULL, 'Team Photo - Costa Rica', FALSE),
(1, 'COS14', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS15', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS16', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS17', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS18', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS19', NULL, 'Player - Costa Rica', FALSE),
(1, 'COS20', NULL, 'Player - Costa Rica', FALSE),
(1, 'PAN1', NULL, 'Team Badge - Panama', TRUE),
(1, 'PAN2', NULL, 'Player - Panama', FALSE),
(1, 'PAN3', NULL, 'Player - Panama', FALSE),
(1, 'PAN4', NULL, 'Player - Panama', FALSE),
(1, 'PAN5', NULL, 'Player - Panama', FALSE),
(1, 'PAN6', NULL, 'Player - Panama', FALSE),
(1, 'PAN7', NULL, 'Player - Panama', FALSE),
(1, 'PAN8', NULL, 'Player - Panama', FALSE),
(1, 'PAN9', NULL, 'Player - Panama', FALSE),
(1, 'PAN10', NULL, 'Player - Panama', FALSE),
(1, 'PAN11', NULL, 'Player - Panama', FALSE),
(1, 'PAN12', NULL, 'Player - Panama', FALSE),
(1, 'PAN13', NULL, 'Team Photo - Panama', FALSE),
(1, 'PAN14', NULL, 'Player - Panama', FALSE),
(1, 'PAN15', NULL, 'Player - Panama', FALSE),
(1, 'PAN16', NULL, 'Player - Panama', FALSE),
(1, 'PAN17', NULL, 'Player - Panama', FALSE),
(1, 'PAN18', NULL, 'Player - Panama', FALSE),
(1, 'PAN19', NULL, 'Player - Panama', FALSE),
(1, 'PAN20', NULL, 'Player - Panama', FALSE),
(1, 'JAM1', NULL, 'Team Badge - Jamaica', TRUE),
(1, 'JAM2', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM3', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM4', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM5', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM6', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM7', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM8', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM9', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM10', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM11', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM12', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM13', NULL, 'Team Photo - Jamaica', FALSE),
(1, 'JAM14', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM15', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM16', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM17', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM18', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM19', NULL, 'Player - Jamaica', FALSE),
(1, 'JAM20', NULL, 'Player - Jamaica', FALSE),
(1, 'HON1', NULL, 'Team Badge - Honduras', TRUE),
(1, 'HON2', NULL, 'Player - Honduras', FALSE),
(1, 'HON3', NULL, 'Player - Honduras', FALSE),
(1, 'HON4', NULL, 'Player - Honduras', FALSE),
(1, 'HON5', NULL, 'Player - Honduras', FALSE),
(1, 'HON6', NULL, 'Player - Honduras', FALSE),
(1, 'HON7', NULL, 'Player - Honduras', FALSE),
(1, 'HON8', NULL, 'Player - Honduras', FALSE),
(1, 'HON9', NULL, 'Player - Honduras', FALSE),
(1, 'HON10', NULL, 'Player - Honduras', FALSE),
(1, 'HON11', NULL, 'Player - Honduras', FALSE),
(1, 'HON12', NULL, 'Player - Honduras', FALSE),
(1, 'HON13', NULL, 'Team Photo - Honduras', FALSE),
(1, 'HON14', NULL, 'Player - Honduras', FALSE),
(1, 'HON15', NULL, 'Player - Honduras', FALSE),
(1, 'HON16', NULL, 'Player - Honduras', FALSE),
(1, 'HON17', NULL, 'Player - Honduras', FALSE),
(1, 'HON18', NULL, 'Player - Honduras', FALSE),
(1, 'HON19', NULL, 'Player - Honduras', FALSE),
(1, 'HON20', NULL, 'Player - Honduras', FALSE),
(1, 'NEW1', NULL, 'Team Badge - New Zealand', TRUE),
(1, 'NEW2', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW3', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW4', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW5', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW6', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW7', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW8', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW9', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW10', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW11', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW12', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW13', NULL, 'Team Photo - New Zealand', FALSE),
(1, 'NEW14', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW15', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW16', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW17', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW18', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW19', NULL, 'Player - New Zealand', FALSE),
(1, 'NEW20', NULL, 'Player - New Zealand', FALSE),
(1, 'NIG1', NULL, 'Team Badge - Nigeria', TRUE),
(1, 'NIG2', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG3', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG4', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG5', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG6', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG7', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG8', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG9', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG10', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG11', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG12', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG13', NULL, 'Team Photo - Nigeria', FALSE),
(1, 'NIG14', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG15', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG16', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG17', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG18', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG19', NULL, 'Player - Nigeria', FALSE),
(1, 'NIG20', NULL, 'Player - Nigeria', FALSE),
(1, 'EGY1', NULL, 'Team Badge - Egypt', TRUE),
(1, 'EGY2', NULL, 'Player - Egypt', FALSE),
(1, 'EGY3', NULL, 'Player - Egypt', FALSE),
(1, 'EGY4', NULL, 'Player - Egypt', FALSE),
(1, 'EGY5', NULL, 'Player - Egypt', FALSE),
(1, 'EGY6', NULL, 'Player - Egypt', FALSE),
(1, 'EGY7', NULL, 'Player - Egypt', FALSE),
(1, 'EGY8', NULL, 'Player - Egypt', FALSE),
(1, 'EGY9', NULL, 'Player - Egypt', FALSE),
(1, 'EGY10', NULL, 'Player - Egypt', FALSE),
(1, 'EGY11', NULL, 'Player - Egypt', FALSE),
(1, 'EGY12', NULL, 'Player - Egypt', FALSE),
(1, 'EGY13', NULL, 'Team Photo - Egypt', FALSE),
(1, 'EGY14', NULL, 'Player - Egypt', FALSE),
(1, 'EGY15', NULL, 'Player - Egypt', FALSE),
(1, 'EGY16', NULL, 'Player - Egypt', FALSE),
(1, 'EGY17', NULL, 'Player - Egypt', FALSE),
(1, 'EGY18', NULL, 'Player - Egypt', FALSE),
(1, 'EGY19', NULL, 'Player - Egypt', FALSE),
(1, 'EGY20', NULL, 'Player - Egypt', FALSE),
(1, 'ALG1', NULL, 'Team Badge - Algeria', TRUE),
(1, 'ALG2', NULL, 'Player - Algeria', FALSE),
(1, 'ALG3', NULL, 'Player - Algeria', FALSE),
(1, 'ALG4', NULL, 'Player - Algeria', FALSE),
(1, 'ALG5', NULL, 'Player - Algeria', FALSE),
(1, 'ALG6', NULL, 'Player - Algeria', FALSE),
(1, 'ALG7', NULL, 'Player - Algeria', FALSE),
(1, 'ALG8', NULL, 'Player - Algeria', FALSE),
(1, 'ALG9', NULL, 'Player - Algeria', FALSE),
(1, 'ALG10', NULL, 'Player - Algeria', FALSE),
(1, 'ALG11', NULL, 'Player - Algeria', FALSE),
(1, 'ALG12', NULL, 'Player - Algeria', FALSE),
(1, 'ALG13', NULL, 'Team Photo - Algeria', FALSE),
(1, 'ALG14', NULL, 'Player - Algeria', FALSE),
(1, 'ALG15', NULL, 'Player - Algeria', FALSE),
(1, 'ALG16', NULL, 'Player - Algeria', FALSE),
(1, 'ALG17', NULL, 'Player - Algeria', FALSE),
(1, 'ALG18', NULL, 'Player - Algeria', FALSE),
(1, 'ALG19', NULL, 'Player - Algeria', FALSE),
(1, 'ALG20', NULL, 'Player - Algeria', FALSE),
(1, 'SOU11', NULL, 'Team Badge - South Africa', TRUE),
(1, 'SOU12', NULL, 'Player - South Africa', FALSE),
(1, 'SOU13', NULL, 'Player - South Africa', FALSE),
(1, 'SOU14', NULL, 'Player - South Africa', FALSE),
(1, 'SOU15', NULL, 'Player - South Africa', FALSE),
(1, 'SOU16', NULL, 'Player - South Africa', FALSE),
(1, 'SOU17', NULL, 'Player - South Africa', FALSE),
(1, 'SOU18', NULL, 'Player - South Africa', FALSE),
(1, 'SOU19', NULL, 'Player - South Africa', FALSE),
(1, 'SOU110', NULL, 'Player - South Africa', FALSE),
(1, 'SOU111', NULL, 'Player - South Africa', FALSE),
(1, 'SOU112', NULL, 'Player - South Africa', FALSE),
(1, 'SOU113', NULL, 'Team Photo - South Africa', FALSE),
(1, 'SOU114', NULL, 'Player - South Africa', FALSE),
(1, 'SOU115', NULL, 'Player - South Africa', FALSE),
(1, 'SOU116', NULL, 'Player - South Africa', FALSE),
(1, 'SOU117', NULL, 'Player - South Africa', FALSE),
(1, 'SOU118', NULL, 'Player - South Africa', FALSE),
(1, 'SOU119', NULL, 'Player - South Africa', FALSE),
(1, 'SOU120', NULL, 'Player - South Africa', FALSE),
(1, 'IVO1', NULL, 'Team Badge - Ivory Coast', TRUE),
(1, 'IVO2', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO3', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO4', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO5', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO6', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO7', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO8', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO9', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO10', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO11', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO12', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO13', NULL, 'Team Photo - Ivory Coast', FALSE),
(1, 'IVO14', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO15', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO16', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO17', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO18', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO19', NULL, 'Player - Ivory Coast', FALSE),
(1, 'IVO20', NULL, 'Player - Ivory Coast', FALSE),
(1, 'NOR1', NULL, 'Team Badge - Norway', TRUE),
(1, 'NOR2', NULL, 'Player - Norway', FALSE),
(1, 'NOR3', NULL, 'Player - Norway', FALSE),
(1, 'NOR4', NULL, 'Player - Norway', FALSE),
(1, 'NOR5', NULL, 'Player - Norway', FALSE),
(1, 'NOR6', NULL, 'Player - Norway', FALSE),
(1, 'NOR7', NULL, 'Player - Norway', FALSE),
(1, 'NOR8', NULL, 'Player - Norway', FALSE),
(1, 'NOR9', NULL, 'Player - Norway', FALSE),
(1, 'NOR10', NULL, 'Player - Norway', FALSE),
(1, 'NOR11', NULL, 'Player - Norway', FALSE),
(1, 'NOR12', NULL, 'Player - Norway', FALSE),
(1, 'NOR13', NULL, 'Team Photo - Norway', FALSE),
(1, 'NOR14', NULL, 'Player - Norway', FALSE),
(1, 'NOR15', NULL, 'Player - Norway', FALSE),
(1, 'NOR16', NULL, 'Player - Norway', FALSE),
(1, 'NOR17', NULL, 'Player - Norway', FALSE),
(1, 'NOR18', NULL, 'Player - Norway', FALSE),
(1, 'NOR19', NULL, 'Player - Norway', FALSE),
(1, 'NOR20', NULL, 'Player - Norway', FALSE),
(1, 'AUS11', NULL, 'Team Badge - Austria', TRUE),
(1, 'AUS12', NULL, 'Player - Austria', FALSE),
(1, 'AUS13', NULL, 'Player - Austria', FALSE),
(1, 'AUS14', NULL, 'Player - Austria', FALSE),
(1, 'AUS15', NULL, 'Player - Austria', FALSE),
(1, 'AUS16', NULL, 'Player - Austria', FALSE),
(1, 'AUS17', NULL, 'Player - Austria', FALSE),
(1, 'AUS18', NULL, 'Player - Austria', FALSE),
(1, 'AUS19', NULL, 'Player - Austria', FALSE),
(1, 'AUS110', NULL, 'Player - Austria', FALSE),
(1, 'AUS111', NULL, 'Player - Austria', FALSE),
(1, 'AUS112', NULL, 'Player - Austria', FALSE),
(1, 'AUS113', NULL, 'Team Photo - Austria', FALSE),
(1, 'AUS114', NULL, 'Player - Austria', FALSE),
(1, 'AUS115', NULL, 'Player - Austria', FALSE),
(1, 'AUS116', NULL, 'Player - Austria', FALSE),
(1, 'AUS117', NULL, 'Player - Austria', FALSE),
(1, 'AUS118', NULL, 'Player - Austria', FALSE),
(1, 'AUS119', NULL, 'Player - Austria', FALSE),
(1, 'AUS120', NULL, 'Player - Austria', FALSE),
(1, 'UKR1', NULL, 'Team Badge - Ukraine', TRUE),
(1, 'UKR2', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR3', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR4', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR5', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR6', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR7', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR8', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR9', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR10', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR11', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR12', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR13', NULL, 'Team Photo - Ukraine', FALSE),
(1, 'UKR14', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR15', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR16', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR17', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR18', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR19', NULL, 'Player - Ukraine', FALSE),
(1, 'UKR20', NULL, 'Player - Ukraine', FALSE),
(1, 'SCO1', NULL, 'Team Badge - Scotland', TRUE),
(1, 'SCO2', NULL, 'Player - Scotland', FALSE),
(1, 'SCO3', NULL, 'Player - Scotland', FALSE),
(1, 'SCO4', NULL, 'Player - Scotland', FALSE),
(1, 'SCO5', NULL, 'Player - Scotland', FALSE),
(1, 'SCO6', NULL, 'Player - Scotland', FALSE),
(1, 'SCO7', NULL, 'Player - Scotland', FALSE),
(1, 'SCO8', NULL, 'Player - Scotland', FALSE),
(1, 'SCO9', NULL, 'Player - Scotland', FALSE),
(1, 'SCO10', NULL, 'Player - Scotland', FALSE),
(1, 'SCO11', NULL, 'Player - Scotland', FALSE),
(1, 'SCO12', NULL, 'Player - Scotland', FALSE),
(1, 'SCO13', NULL, 'Team Photo - Scotland', FALSE),
(1, 'SCO14', NULL, 'Player - Scotland', FALSE),
(1, 'SCO15', NULL, 'Player - Scotland', FALSE),
(1, 'SCO16', NULL, 'Player - Scotland', FALSE),
(1, 'SCO17', NULL, 'Player - Scotland', FALSE),
(1, 'SCO18', NULL, 'Player - Scotland', FALSE),
(1, 'SCO19', NULL, 'Player - Scotland', FALSE),
(1, 'SCO20', NULL, 'Player - Scotland', FALSE),
(1, 'PAR1', NULL, 'Team Badge - Paraguay', TRUE),
(1, 'PAR2', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR3', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR4', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR5', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR6', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR7', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR8', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR9', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR10', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR11', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR12', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR13', NULL, 'Team Photo - Paraguay', FALSE),
(1, 'PAR14', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR15', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR16', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR17', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR18', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR19', NULL, 'Player - Paraguay', FALSE),
(1, 'PAR20', NULL, 'Player - Paraguay', FALSE);